CHANGELOG.md, Cargo.lock, README.adoc, deploy/config-spec/properties.yaml, deploy/crd/hbasecluster.crd.yaml, docs/modules/ROOT/pages/building.adoc, docs/modules/ROOT/pages/index.adoc, docs/modules/ROOT/pages/usage.adoc, examples/simple-hbase-cluster.yaml, rust/crd/Cargo.toml, rust/crd/src/lib.rs, rust/operator-binary/Cargo.toml, rust/operator/Cargo.toml, rust/operator/src/lib.rs
fixes https://github.com/stackabletech/hbase-operator/issues/21
For testing we need to create hbase directory for now:
```
export HADOOP_USER_NAME=root
./hdfs dfs -mkdir hdfs://<namenode>:9000/hbase; ./hdfs dfs -chown stackable hdfs://<namenode>:9000/hbase
```
=> Adapt to use docker images

CHANGELOG.md, deploy/helm/hbase-operator/crds/crds.yaml, rust/crd/src/lib.rs
Add missing crd defaults (#360)
(cherry picked from commit 45f104095fab9e238cd838160198924e12a39d3a)
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)
=> Add missing crd defaults to 23.4

docs/modules/hbase/examples/getting_started/hbase.yaml, docs/modules/hbase/examples/getting_started/hdfs.yaml, docs/modules/hbase/examples/getting_started/znode.yaml, docs/modules/hbase/pages/getting_started/first_steps.adoc, docs/modules/hbase/pages/usage-guide/discovery.adoc
Clarified the use of ZookeeeperZnode reference in HBase config in the HBase operator docs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Clarified the use of ZookeeeperZnode reference in HBase config

CHANGELOG.md, rust/crd/src/lib.rs
Default `hbase.unsafe.regionserver.hostname.disable.master.reversedns` to `true`, to ensure the names of RegionServers are resolved to their hostnames instead of IP addresses.
If desired, this option can be reset to `false` in `configOverrides` at the rolegroup level, but not at the role level (see stackabletech/operator-rs#339).
Closes #405 
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Disable reverse DNS lookup for RegionServers

docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: Add example to pod placement

tests/templates/kuttl/kerberos/11-install-hdfs.yaml.j2, tests/templates/kuttl/smoke/20-install-hdfs.yaml.j2
Breaking changes from https://github.com/stackabletech/hdfs-operator/pull/450
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix(tests): Adopt breaking changes from HDFS listener integration

Cargo.lock, Cargo.toml, rust/operator-binary/build.rs, rust/operator-binary/src/hbase_controller.rs, rust/operator-binary/src/main.rs
This requires some code changes as well, as 0.7 contained breaking changes. This gets rid of GHSA-22q8-ghmq-63vf since the transitive dependency libgit2 is updated as well.
We can also revert some custom code that was used to pull variables from the env at build time, since built was unable to get them from the environment due to the way that build-rust-crate provisioned the environment
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Update built to 0.7.1.

tests/templates/kuttl/kerberos/00-rbac.yaml.j2, tests/templates/kuttl/kerberos/01-install-krb5-kdc.yaml.j2, tests/templates/kuttl/kerberos/20-access-hdfs.yaml.j2, tests/templates/kuttl/kerberos/41-access-hbase.yaml.j2, tests/templates/kuttl/kerberos/42-test-rest-server.yaml, tests/test-definition.yaml
fix: kerberos tests to run on openshift
```
--- PASS: kuttl (1903.04s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/smoke_hbase-2.4.17_hdfs-3.3.6_zookeeper-3.8.3_listener-class-external-unstable (379.60s)
--- PASS: kuttl/harness/logging_hbase-2.4.17_hdfs-latest-3.3.6_zookeeper-latest-3.8.3 (210.53s)
--- PASS: kuttl/harness/cluster-operation_hbase-latest-2.4.17_hdfs-latest-3.3.6_zookeeper-latest-3.8.3 (239.90s)
--- PASS: kuttl/harness/orphaned_resources_hbase-latest-2.4.17_hdfs-latest-3.3.6_zookeeper-latest-3.8.3 (199.59s)
--- PASS: kuttl/harness/resources_hbase-latest-2.4.17_hdfs-latest-3.3.6_zookeeper-latest-3.8.3 (184.67s)
--- PASS: kuttl/harness/kerberos_hbase-2.4.17_hdfs-latest-3.3.6_zookeeper-latest-3.8.3_listener-class-external-unstable_kerberos-realm-PROD.MYCORP_kerberos- …
```
=> fix: kerberos tests to run on openshift

tests/release.yaml, tests/templates/kuttl/cluster-operation/00-patch-ns.yaml.j2, tests/templates/kuttl/kerberos/00-patch-ns.yaml.j2, tests/templates/kuttl/logging/00-patch-ns.yaml.j2, tests/templates/kuttl/orphaned_resources/00-patch-ns.yaml.j2, tests/templates/kuttl/profiling/00-patch-ns.yaml.j2, tests/templates/kuttl/resources/00-patch-ns.yaml.j2, tests/templates/kuttl/smoke/00-patch-ns.yaml.j2, tests/test-definition.yaml
Part of stackabletech/issues#566.
OKD:
```
--- PASS: kuttl (939.31s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/cluster-operation_hbase-latest-2.4.17_hdfs-latest-3.3.6_zookeeper-latest-3.9.1_openshift-true (279.22s)
--- PASS: kuttl/harness/smoke_hbase-2.4.17_hdfs-3.3.6_zookeeper-3.8.3_listener-class-external-unstable_openshift-true (309.81s)
--- PASS: kuttl/harness/orphaned_resources_hbase-latest-2.4.17_hdfs-latest-3.3.6_zookeeper-latest-3.9.1_openshift-true (184.70s)
--- PASS: kuttl/harness/profiling_hbase-2.4.17_hdfs-latest-3.3.6_zookeeper-latest-3.9.1_openshift-true (190.50s)
--- PASS: kuttl/harness/resources_hbase-latest-2.4.17_hdfs-latest-3.3.6_zookeeper-latest-3.9.1_openshift-true (191.40s)
--- PASS: kuttl/harness/logging_hbase-2.4.17_hdfs-latest-3.3.6_zookeeper-latest-3 …
```
=> tests: added namespace patch for openshift tests

tests/templates/kuttl/kerberos/01-install-krb5-kdc.yaml.j2, tests/test-definition.yaml
Update the krb5 image in the integration tests
The krb5 version was upgraded from 1.18.2 to 1.21.1 in stackabletech/docker-images#627. As the image with version 1.18.2 is not built anymore, it must be replaced in all integration tests.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Update the krb5 image in the integration tests

tests/test-definition.yaml
Update the ZooKeeper image in the integration tests
The ZooKeeper version was upgraded from 3.9.1 to 3.9.2 in stackabletech/docker-images#592. As the image with version 3.9.1 is not built anymore, it must be replaced in all integration tests.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Update the ZooKeeper image in the integration tests

tests/templates/kuttl/snapshot-export/10-install-minio.yaml.j2, tests/templates/kuttl/snapshot-export/10_helm-bitnami-minio-values.yaml.j2
The integration tests fail on an IONOS cluster because MinIO cannot be deployed due to the following error:
> failed to provision volume with StorageClass "ionos-enterprise-hdd": rpc error: code = OutOfRange desc = requested size 67108864 must be between 1073741824 and 4398046511104 bytes
A PersistentVolumeClaim with 64 MiB is created which is not supported. Instead of requesting 1 GiB, an emptyDir is now used instead.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Use an emptyDir instead of a persistentVolumeClaim for MinIO in the integration tests

tests/templates/kuttl/omid/40-install-omid.yaml.j2
Fix the Omid test
The Omid test failed in the test step `40-install-omid` due to an invalid image name:
> Failed to apply default image tag "docker.stackable.tech/stackable/omid:\\"1.1.0\\"-stackable0.0.0-dev": couldn't parse image name "docker.stackable.tech/stackable/omid:\\"1.1.0\\"-stackable0.0.0-dev": invalid reference format
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Fix the Omid test

docs/modules/hbase/pages/usage.adoc
docs: remove home module from refs (stackabletech/documentation#637) / 23.1
=> docs: remove home module from refs (stackabletech/documentation#637) / 23.1

docs/modules/hbase/pages/usage-guide/logging.adoc, docs/modules/hbase/pages/usage-guide/monitoring.adoc, docs/modules/hbase/pages/usage-guide/resource-requests.adoc
docs: remove home module from refs (stackabletech/documentation#637) / 23.4
=> docs: remove home module from refs (stackabletech/documentation#637) / 23.4

docs/modules/hbase/pages/usage-guide/logging.adoc, docs/modules/hbase/pages/usage-guide/monitoring.adoc, docs/modules/hbase/pages/usage-guide/resource-requests.adoc
docs: remove home module from refs (stackabletech/documentation#637) / 23.7
=> docs: remove home module from refs (stackabletech/documentation#637) / 23.7

docs/modules/hbase/pages/usage-guide/resource-requests.adoc
docs: remove home module from refs (stackabletech/documentation#637) / 24.7
=> docs: remove home module from refs (stackabletech/documentation#637) / 24.7

docs/modules/hbase/pages/usage-guide/logging.adoc, docs/modules/hbase/pages/usage-guide/monitoring.adoc, docs/modules/hbase/pages/usage-guide/resource-requests.adoc, docs/modules/hbase/pages/usage-guide/security.adoc
docs: remove home module from refs (stackabletech/documentation#637) / 24.3
=> docs: remove home module from refs (stackabletech/documentation#637) / 24.3

tests/templates/kuttl/overrides/31-assert.yaml
As [@NickLarsenNZ](https://github.com/NickLarsenNZ) pointed out we could get better in code style and readability. This are suggested changes of him first used in https://github.com/stackabletech/superset-operator/pull/533 and now being propagated through operators.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Adopting according to new readability and code style

CHANGELOG.md, tests/templates/kuttl/omid/40-assert.yaml, tests/templates/kuttl/omid/40-install-omid.yaml.j2, tests/test-definition.yaml
part of https://github.com/stackabletech/docker-images/issues/834
:green_circle: CI: https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hbase-operator-it-custom/16/
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore(tests): update omid version

docs/modules/hbase/pages/getting_started/first_steps.adoc, docs/modules/hbase/pages/getting_started/index.adoc, docs/modules/hbase/pages/getting_started/installation.adoc, docs/modules/hbase/pages/index.adoc, docs/modules/hbase/pages/usage-guide/compression.adoc, docs/modules/hbase/pages/usage-guide/hbck2.adoc, docs/modules/hbase/pages/usage-guide/logging.adoc, docs/modules/hbase/pages/usage-guide/monitoring.adoc, docs/modules/hbase/pages/usage-guide/overrides.adoc, docs/modules/hbase/pages/usage-guide/phoenix.adoc, docs/modules/hbase/pages/usage-guide/resource-requests.adoc, docs/modules/hbase/pages/usage-guide/security.adoc, docs/modules/hbase/pages/usage-guide/snapshot-export.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Add descriptions

docs/modules/hbase/pages/usage-guide/adls.adoc, docs/modules/hbase/partials/nav.adoc
Describe how to use ADLS instead of HDFS
The ADLS support could also be properly implemented into the operator. The CRD could be extended and the operator could create the ConfigMap for ADLS. On the one hand, this would be a lot of work, on the other hand, this cannot be tested without an actual Azure storage account. Azure storage clones like Azurite do currently not support ADLS Gen2, see 
[Azure/Azurite#553](https://www.github.com/Azure/Azurite/issues/553). Adding a feature which cannot be integrated into Stackable's test landscape, is not sensible. And as the hurdle is low for the customer to define the ADLS ConfigMap themselves, only a documentation is provided.
Closes #539 
- Not all of these items are applicable to all PRs, the author should update this template to only leave the …
=> docs: Describe how to use ADLS instead of HDFS

CHANGELOG.md, Cargo.lock, Cargo.toml, deploy/helm/hbase-operator/crds/crds.yaml, rust/operator-binary/src/hbase_controller.rs
part of: https://github.com/stackabletech/issues/issues/640
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: bump op-rs

docs/modules/hbase/pages/getting_started/first_steps.adoc, docs/modules/hbase/pages/getting_started/index.adoc, docs/modules/hbase/pages/getting_started/installation.adoc, docs/modules/hbase/pages/index.adoc, docs/modules/hbase/pages/reference/commandline-parameters.adoc, docs/modules/hbase/pages/reference/environment-variables.adoc, docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc, docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc, docs/modules/hbase/pages/usage-guide/overrides.adoc, docs/modules/hbase/pages/usage-guide/phoenix.adoc, docs/modules/hbase/pages/usage-guide/security.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: pod overrides, better install instructions, improved wording

CHANGELOG.md, rust/operator-binary/src/hbase_controller.rs, rust/operator-binary/src/main.rs
Part of: https://github.com/stackabletech/issues/issues/211
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: don't stop the reconciliation if one cluster is invalid

docs/modules/hbase/pages/reference/environment-variables.adoc
Adds missing KUBERNETES_CLUSTER_DOMAIN environment variable to docs.
part of stackabletech/issues#668
=> Adds missing KUBERNETES_CLUSTER_DOMAIN environment variable to docs.

CHANGELOG.md, deploy/config-spec/properties.yaml, deploy/helm/hbase-operator/configs/properties.yaml, rust/crd/src/lib.rs
The problem was defaulting in the product config callbacks like:
```
result.insert( 
HBASE_ROOTDIR.to_string(), 
Some( 
self.hbase_rootdir 
.as_deref() 
.unwrap_or(HBASE_ROOT_DIR_DEFAULT) 
.to_string(), 
), 
); 
```
If the `hbaseRootdir` was only set on the role, we defaulted the rolegroup to `HBASE_ROOT_DIR_DEFAULT` ("/hbase"), which during merging overrode the value set on the role. The solution here is to remove the defaulting and it works.
One problem remained, if `hbaseRootdir` was not set at all, there was no default set anymore. The product config did not add the default due to the field being marked as not required.
In order to keep the defaulting behavior as is and not mess with existing defaulted installation, the default for `hbase.root.dir` in the product config was changed to …
=> Fix bug where the configuration of the hbaseRootdir at the role level is ignored

docs/modules/hbase/examples/getting_started/getting_started.sh, docs/modules/hbase/examples/getting_started/install_output.txt, docs/modules/hbase/examples/usage-guide/hbck2-job.yaml, docs/modules/hbase/examples/usage-guide/snapshot-export-job.yaml
Part of https://github.com/stackabletech/issues/issues/647.
=> docs: Update release in getting_started

docs/modules/hbase/examples/getting_started/getting_started.sh, docs/modules/hbase/examples/getting_started/getting_started.sh.j2
Part of https://github.com/stackabletech/issues/issues/611.
Depends on https://github.com/stackabletech/hbase-operator/pull/589.
=> chore(getting_started): Replace templating instructions with make

tests/templates/kuttl/opa/11-install-opa.yaml.j2, tests/test-definition.yaml
Part of https://github.com/stackabletech/issues/issues/647.
Replace hard-coded OPA version with a templated dimension.
There is a companion change for the release-24.11 branch: #593.
Similar change made here https://github.com/stackabletech/hdfs-operator/pull/614.
=> tests: Add OPA as a test dimension (main)

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, Makefile, crate-hashes.json, docs/modules/hbase/examples/getting_started/getting_started.sh, docs/modules/hbase/examples/getting_started/getting_started.sh.j2, rust/operator-binary/src/hbase_controller.rs
Add the following PRs to the release 24.11:
* #589 
* #590 
* #592 
* #594
=> Update release branch

CHANGELOG.md, Cargo.lock, Cargo.toml, deploy/helm/hbase-operator/crds/crds.yaml, rust/crd/src/lib.rs, rust/operator-binary/src/hbase_controller.rs, rust/operator-binary/src/kerberos.rs
Part of: https://github.com/stackabletech/issues/issues/586
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Support setting TLS certificate lifetimes

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, deploy/helm/hbase-operator/templates/roles.yaml, rust/crd/src/lib.rs, rust/operator-binary/Cargo.toml, rust/operator-binary/src/hbase_controller.rs, rust/operator-binary/src/main.rs
Part of https://github.com/stackabletech/operator-rs/issues/942
```[tasklist]
```
=> chore: Update to operator-rs 0.84.1

docs/modules/hbase/examples/rego/hbase.rego, docs/modules/hbase/examples/rego/hbase_test.rego, docs/modules/hbase/examples/usage-guide/hbase-regorules.yaml, docs/modules/hbase/pages/usage-guide/security.adoc, tests/templates/kuttl/opa/12-rego-rules.txt.j2, tests/test-definition.yaml
Part of: https://github.com/stackabletech/docker-images/issues/969
```
=== NAME  kuttl
harness.go:407: run tests finished
harness.go:515: cleaning up
harness.go:572: removing temp folder: ""
--- PASS: kuttl (260.54s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/opa_hbase-opa-2.6.0_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_krb5-1.21.1_opa-1.0.0_openshift-false (260.41s)
PASS
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore(opa): bump to 1.0.0 in integration tests and docs

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, deploy/helm/hbase-operator/crds/crds.yaml, deploy/helm/hbase-operator/values.yaml, docs/modules/hbase/examples/usage-guide/hbck2-job.yaml, docs/modules/hbase/examples/usage-guide/hbck2-job.yaml.j2, docs/modules/hbase/examples/usage-guide/snapshot-export-job.yaml, docs/modules/hbase/examples/usage-guide/snapshot-export-job.yaml.j2, docs/modules/hbase/pages/reference/environment-variables.adoc, rust/operator-binary/src/hbase_controller.rs, tests/templates/kuttl/kerberos/01-install-krb5-kdc.yaml.j2, tests/templates/kuttl/kerberos/20-access-hdfs.yaml.j2, tests/templates/kuttl/kerberos/41-access-hbase.yaml.j2, tests/templates/kuttl/kerberos/42-test-rest-server.yaml, tests/templates/kuttl/logging/06-install-hbase-test-runner.yaml, tests/templates/kuttl/omid/40-install-omid.yaml.j2, tests/templates/kuttl/opa/01-install-krb5-kdc.yaml.j2, tests/templates/kuttl/opa/41-access-hbase.yaml.j2, tests/templates/kuttl/opa/42-test-rest-server.yaml, tests/templates/kuttl/profiling/04-install-test-container.yaml, tests/templates/kuttl/smoke/40-install-hbase-test-runner.yaml, tests/test-definition.yaml
```
--- FAIL: kuttl (6533.87s)
--- FAIL: kuttl/harness (0.00s)
--- PASS: kuttl/harness/smoke_hbase-2.6.0_hdfs-3.4.0_zookeeper-3.9.2_listener-class-external-unstable_openshift-false (533.79s)
--- PASS: kuttl/harness/cluster-operation_hbase-latest-2.6.0_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_openshift-false (533.89s)
--- PASS: kuttl/harness/smoke_hbase-2.6.0_hdfs-3.4.0_zookeeper-3.9.2_listener-class-cluster-internal_openshift-false (299.96s)
--- PASS: kuttl/harness/omid_hbase-2.4.18_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_openshift-false_omid-1.1.2 (300.07s)
--- PASS: kuttl/harness/smoke_hbase-2.6.0_hdfs-3.3.6_zookeeper-3.9.2_listener-class-cluster-internal_openshift-false (299.95s)
--- PASS: kuttl/harness/smoke_hbase-2.6.0_hdfs-3.3.6_zookeeper-3.9.2_listener-class-external-unstable_opens …
```
=> chore: add oci references, merge templating changes

CHANGELOG.md, deploy/helm/hbase-operator/crds/crds.yaml, docs/modules/hbase/pages/usage-guide/overrides.adoc, rust/crd/src/lib.rs, rust/operator-binary/src/config/jvm.rs, rust/operator-binary/src/config/mod.rs, rust/operator-binary/src/hbase_controller.rs, rust/operator-binary/src/kerberos.rs, rust/operator-binary/src/main.rs, tests/templates/kuttl/omid/40-install-omid.yaml.j2
Part of https://github.com/stackabletech/issues/issues/584
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat!: Support configuring JVM arguments

deploy/helm/hbase-operator/crds/crds.yaml, rust/crd/src/lib.rs, rust/operator-binary/src/config/jvm.rs
Fixup of https://github.com/stackabletech/hbase-operator/pull/570
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: region mover merging oversight

CHANGELOG.md, docs/modules/hbase/partials/supported-versions.adoc, tests/templates/kuttl/snapshot-export/30_test-export.sh, tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/972
I had to add the `--no-checksum-verify` flag when exporting snapshots to/from S3, because our `snapshot-export` test was failing for HBase 2.6.1.
From what I see, checksum verification was merged and released with 2.6.1: https://issues.apache.org/jira/browse/HBASE-28625
However, it seems to have problems when comparing snapshots on different filesystems (like HDFS and S3).
https://issues.apache.org/jira/browse/HBASE-28702 was also merged into 2.6.1 and seems to introduce a flag to skip checksum-checks between snapshots when exporting tables. I'm not sure if this flag is supposed to work with snapshot exports as well, at least I could not make it work. Setting `fs.checksum.combine.mode` to `COMPOSITE_CRC` also does not seem …
=> chore: support for hbase 2.6.1

docs/modules/hbase/pages/usage-guide/overrides.adoc
Hopefully fixes
```
[11:54:01.505] WARN (asciidoctor): skipping reference to missing attribute: hbase_home
file: docs/modules/hbase/pages/usage-guide/overrides.adoc
source: https://github.com/stackabletech/hbase-operator.git (branch: main | start path: docs)
[11:54:01.507] WARN (asciidoctor): skipping reference to missing attribute: hbase_home
file: docs/modules/hbase/pages/usage-guide/overrides.adoc
source: https://github.com/stackabletech/hbase-operator.git (branch: main | start path: docs)
```
=> docs: Fix rendering

docs/modules/hbase/examples/getting_started/getting_started.sh, docs/modules/hbase/examples/getting_started/getting_started.sh.j2, docs/modules/hbase/pages/getting_started/first_steps.adoc, docs/modules/hbase/pages/getting_started/installation.adoc, docs/templating_vars.yaml
Part of https://github.com/stackabletech/infrastructure/issues/142
Updating the helm install commands in Getting started sections of the operators was missed during Harbor migration of the docs.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: Update helm install commands

CHANGELOG.md, tests/templates/kuttl/opa/11-install-opa.yaml.j2, tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1084.
=> test: Bump OPA to 1.4.2

CHANGELOG.md, rust/operator-binary/src/hbase_controller.rs
Part of https://github.com/stackabletech/issues/issues/651
Remove hardcoded uid and gid, they'll default to the ones from the docker images now.
For 25.7 that means they might change from 1000/0
See https://github.com/stackabletech/docker-images/pull/916 for details
=> chore: Remove hardcoded uid and gid

Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, rust/operator-binary/src/hbase_controller.rs
_This was supposed to be part of https://github.com/stackabletech/issues/issues/642, but this operator doesn't use the common s3, tls, listener, authentication crd structs._
=> chore: Bump stackable_operator to 0.93.1

tests/templates/kuttl/snapshot-export/30_test-export.sh
In #659, comments were added within the export command which broke it. Now, there are separate exports, increasing the changeability.
=> test(snapshot-export): Fix the test script

CHANGELOG.md, deploy/helm/hbase-operator/templates/roles.yaml
Needed since https://github.com/stackabletech/operator-rs/pull/938
Not 100% sure why the product needs this, but it was this way before.
=> fix: Add RBAC permission to patch events

docs/modules/hbase/partials/supported-versions.adoc
Apache HBase 2.6.2 is the LTS version and 2.6.1 was deprecated in SDP 25.7.0. This is cherry-picked from e3ad7c0 (#684).
=> docs: Fix supported versions (cherry-pick)

docs/modules/hbase/examples/getting_started/zk.yaml, docs/modules/hbase/examples/getting_started/zk.yaml.j2, tests/templates/kuttl/snapshot-export/10_helm-bitnami-minio-values.yaml.j2, tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1275
```
--- FAIL: kuttl (6923.92s)
--- FAIL: kuttl/harness (0.00s)
--- PASS: kuttl/harness/resources_hbase-latest-2.6.2_hdfs-latest-3.4.1_zookeeper-latest-3.9.4_openshift-false (183.82s)
--- PASS: kuttl/harness/overrides_hbase-latest-2.6.2_hdfs-latest-3.4.1_zookeeper-latest-3.9.4_openshift-false (246.90s)
--- PASS: kuttl/harness/orphaned_resources_hbase-latest-2.6.2_hdfs-latest-3.4.1_zookeeper-latest-3.9.4_openshift-false (198.73s)
--- PASS: kuttl/harness/opa_hbase-opa-2.6.2_hdfs-latest-3.4.1_zookeeper-latest-3.9.4_krb5-1.21.1_opa-1.8.0_openshift-false (329.23s)
--- PASS: kuttl/harness/smoke_hbase-2.6.1_hdfs-3.4.1_zookeeper-3.9.3_listener-class-external-unstable_openshift-false (321.09s)
--- PASS: …
```
=> chore: Bump zookeeper version for 25.11.0
