stackabletech/hbase-operator

docs/modules/getting_started/examples/code/getting_started.sh.j2
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)
=> fixed templating

CHANGELOG.md, rust/operator-binary/src/hbase_controller.rs, tests/templates/kuttl/resources/04-assert.yaml
run as group 0 for release 23.4.1
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)
=> run as group 0 for release 23.4.1

Cargo.lock, Cargo.toml, deploy/helm/hbase-operator/crds/crds.yaml, rust/crd/Cargo.toml, rust/operator-binary/Cargo.toml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Switch to workspace dependencies

CHANGELOG.md, deploy/config-spec/properties.yaml, deploy/helm/hbase-operator/configs/properties.yaml, docs/modules/hbase/pages/usage-guide/overrides.adoc, rust/crd/src/lib.rs, rust/operator-binary/src/hbase_controller.rs
CI: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hbase-operator-it-custom/105/
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> JVM config overrides

deploy/helm/hbase-operator/crds/crds.yaml, docs/modules/hbase/pages/usage-guide/listenerclass.adoc, docs/modules/hbase/partials/nav.adoc, rust/crd/src/lib.rs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> ListenerClass docs

CHANGELOG.md, Cargo.lock, rust/operator-binary/src/zookeeper.rs
Fixes https://github.com/stackabletech/hbase-operator/issues/393
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: Hbase zookeeper rootdir calculation

docs/modules/hbase/pages/getting_started/installation.adoc, docs/modules/hbase/pages/index.adoc
Part of https://github.com/stackabletech/stackable-cockpit/pull/101
=> docs: Update references

rust/operator-binary/src/hbase_controller.rs
Part of https://github.com/stackabletech/operator-rs/issues/649
=> refactor: Use operator-rs Duration

Cargo.lock, Cargo.toml, rust/crd/src/lib.rs, rust/operator-binary/Cargo.toml, rust/operator-binary/src/discovery.rs, rust/operator-binary/src/hbase_controller.rs
Part of https://github.com/stackabletech/product-config/issues/95
=> refactor: Use updated product-config

docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: Fix PID 1 description

tests/templates/kuttl/cluster-operation/01-install-zookeeper.yaml.j2, tests/templates/kuttl/logging/02-install-zookeeper.yaml.j2, tests/templates/kuttl/orphaned_resources/01-install-zookeeper.yaml.j2, tests/templates/kuttl/resources/10-install-zookeeper.yaml.j2, tests/templates/kuttl/smoke/10-install-zookeeper.yaml.j2
based on: https://github.com/stackabletech/zookeeper-operator/pull/739
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Updated integration tests for ZooKeeper CRD change

CHANGELOG.md
- Fix missing vector upgrade in changelog
=> Fix vector version in changelog

docs/modules/hbase/examples/usage-guide/hbck2-job.yaml, docs/modules/hbase/pages/usage-guide/operations/cluster-operations.adoc
Document the hbase-operator-tools contained in the HBase image
see stackabletech/docker-images#497
=> Document the hbase-operator-tools contained in the HBase image

docs/modules/hbase/pages/usage-guide/compression.adoc, docs/modules/hbase/partials/nav.adoc
This takes the guesswork out of it for our customers.
We tell them which algorithms are supported and which aren't.
=> Add documentation on supported compression algorithms

tests/templates/kuttl/smoke/test-hbase.py
- fix compression test and use supported compression algorithms
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Fix compression tests

docs/modules/hbase/examples/getting_started/getting_started.sh, docs/modules/hbase/examples/getting_started/getting_started.sh.j2, docs/modules/hbase/examples/getting_started/hbase.yaml.j2, docs/modules/hbase/examples/getting_started/hdfs.yaml.j2, docs/modules/hbase/examples/getting_started/install_output.txt, docs/modules/hbase/examples/getting_started/install_output.txt.j2, docs/modules/hbase/pages/getting_started/installation.adoc, docs/templating_vars.yaml
The listener-operator is now one of the fundamental operators, along with the commons- and secret-operators, and should be mentioned accordingly everywhere.
Add changes from https://github.com/stackabletech/hbase-operator/commit/18396b791591621a67f5b300cabca78a38ad8fe3 to the template file.
```[tasklist]
```
```[tasklist]
```
=> docs: Add listener-operator where missing

docs/modules/hbase/examples/getting_started/hbase.yaml.j2, docs/modules/hbase/examples/getting_started/hdfs.yaml.j2, docs/modules/hbase/examples/usage-guide/hbck2-job.yaml.j2
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs version templating

CHANGELOG.md, Cargo.lock, Cargo.toml, deploy/helm/hbase-operator/crds/crds.yaml, rust/crd/src/lib.rs, rust/operator-binary/src/main.rs
better CRD docs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Better CRD docs

tests/templates/kuttl/cluster-operation/01-install-zookeeper.yaml.j2, tests/templates/kuttl/cluster-operation/02-install-hdfs.yaml.j2, tests/templates/kuttl/cluster-operation/03-install-hbase.yaml.j2, tests/templates/kuttl/cluster-operation/10-pause-hbase.yaml.j2, tests/templates/kuttl/cluster-operation/20-stop-hbase.yaml.j2, tests/templates/kuttl/logging/02-install-zookeeper.yaml.j2, tests/templates/kuttl/logging/03-install-hdfs.yaml.j2, tests/templates/kuttl/logging/04-install-hbase.yaml.j2, tests/templates/kuttl/orphaned_resources/01-install-zookeeper.yaml.j2, tests/templates/kuttl/orphaned_resources/02-install-hdfs.yaml.j2, tests/templates/kuttl/orphaned_resources/03-install-hbase.yaml.j2, tests/templates/kuttl/resources/10-install-zookeeper.yaml.j2, tests/templates/kuttl/resources/20-install-hdfs.yaml.j2, tests/templates/kuttl/resources/30-install-hbase.yaml.j2, tests/templates/kuttl/smoke/10-install-zookeeper.yaml.j2, tests/templates/kuttl/smoke/20-install-hdfs.yaml.j2, tests/templates/kuttl/smoke/30-install-hbase.yaml.j2
Part of https://github.com/stackabletech/issues/issues/481
=> feat(test): pull policy IfNotPresent

CHANGELOG.md, deploy/helm/hbase-operator/templates/_helpers.tpl, deploy/helm/hbase-operator/templates/deployment.yaml, deploy/helm/hbase-operator/templates/roles.yaml, deploy/helm/hbase-operator/values.yaml
Part of: https://github.com/stackabletech/issues/issues/501
=> feat(helm): support labels in values.yaml

deploy/helm/hbase-operator/values.yaml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Add Stackable vendor label to default values.yaml

tests/templates/kuttl/profiling/00-rbac.yaml.j2, tests/templates/kuttl/profiling/04-install-test-container.yaml, tests/test-definition.yaml
```[tasklist]
```
```[tasklist]
```
=> fix(test): running on openshift

Cargo.lock, Cargo.toml, rust/operator-binary/build.rs
This reverts commit f6c1fbfaa433f10d932f9bf02e845a62b24f2f77.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Revert "Update built dependency to 0.7.1 (#452)"

CHANGELOG.md, docs/modules/hbase/partials/supported-versions.adoc, tests/templates/kuttl/logging/01-install-hbase-vector-aggregator.yaml, tests/test-definition.yaml
- remove all 2.4.12 references
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Remove support for 2.4.12

tests/test-definition.yaml
- **fix(tests): update hdfs dependency version**
- **update zookeeper test dependency**
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix(tests): update test dependencies

docs/modules/hbase/pages/usage-guide/logging.adoc, docs/modules/hbase/pages/usage-guide/monitoring.adoc, docs/modules/hbase/pages/usage-guide/security.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: fix links by removing 'home' part of the xref

docs/modules/hbase/examples/usage-guide/hbck2-job.yaml, docs/modules/hbase/examples/usage-guide/hbck2-job.yaml.j2, docs/modules/hbase/examples/usage-guide/snapshot-export-job.yaml, docs/modules/hbase/examples/usage-guide/snapshot-export-job.yaml.j2, docs/modules/hbase/examples/usage-guide/snapshot-export-secret.yaml, docs/modules/hbase/pages/usage-guide/hbck2.adoc, docs/modules/hbase/pages/usage-guide/operations/cluster-operations.adoc, docs/modules/hbase/pages/usage-guide/snapshot-export.adoc, docs/modules/hbase/partials/nav.adoc
Document the snapshot export to S3
Documents #486 
```[tasklist]
```
```[tasklist]
```
=> Document the snapshot export to S3

docs/modules/hbase/pages/index.adoc, docs/modules/hbase/pages/usage-guide/compression.adoc, docs/modules/hbase/pages/usage-guide/hbck2.adoc, docs/modules/hbase/pages/usage-guide/listenerclass.adoc, docs/modules/hbase/pages/usage-guide/logging.adoc, docs/modules/hbase/pages/usage-guide/monitoring.adoc, docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc, docs/modules/hbase/pages/usage-guide/operations/index.adoc, docs/modules/hbase/pages/usage-guide/operations/pod-disruptions.adoc, docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc, docs/modules/hbase/pages/usage-guide/overrides.adoc, docs/modules/hbase/pages/usage-guide/phoenix.adoc, docs/modules/hbase/pages/usage-guide/resource-requests.adoc, docs/modules/hbase/pages/usage-guide/security.adoc, docs/modules/hbase/pages/usage-guide/snapshot-export.adoc
Added Pod override info and formatting cleanup/some minor wording changes.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Hbase docs - cleanup

tests/templates/kuttl/logging/01-install-hbase-vector-aggregator.yaml
Use Vector Helm chart version 0.34.0 (Vector 0.39.0) in the logging test
https://github.com/vectordotdev/helm-charts/blob/vector-0.34.0/CHANGELOG.md#vector-0340---2024-06-17
Implements stackabletech/docker-images#561
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Use Vector Helm chart version 0.34.0 in the logging test

docs/modules/hbase/examples/getting_started/zk.yaml, docs/modules/hbase/examples/getting_started/zk.yaml.j2
Sibling PR to https://github.com/stackabletech/hbase-operator/pull/536
=> chore: Use LTS ZooKeeper

tests/templates/kuttl/logging/01-install-hbase-vector-aggregator.yaml
Part of https://github.com/stackabletech/issues/issues/626
```[tasklist]
```
=> chore: Bump Vector to 0.40.0

deploy/helm/hbase-operator/templates/roles.yaml
See: https://github.com/stackabletech/issues/issues/624
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix(helm): use same scc as olm

Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json
Part of https://github.com/stackabletech/issues/issues/548
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: bump stackable-operator version

CHANGELOG.md, tests/test-definition.yaml
Part of stackabletech/docker-images#832.
```[tasklist]
```
=> chore: Remove ZooKeeper to 3.8.4 from tests

tests/test-definition.yaml
part of https://github.com/stackabletech/docker-images/issues/835
CI: https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hbase-operator-it-custom/17/
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore(tests): bump hdfs version to 3.4.0

tests/templates/kuttl/logging/01-install-hbase-vector-aggregator.yaml
Upgrade the Vector aggregator in the logging tests
The Helm chart version 0.36.1 deploys Vector 0.41.1.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: Upgrade the Vector aggregator in the logging tests

Cargo.lock, Cargo.nix
PR to fix unmaintained crate cargo deny errors
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: bump dependency versions

tests/templates/kuttl/logging/01-install-hbase-vector-aggregator.yaml
Part of https://github.com/stackabletech/docker-images/issues/967
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: Update Vector to 0.43.1 in integration tests

docs/modules/hbase/pages/usage-guide/overrides.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: Fix type Kafka instead of HBase

docs/modules/hbase/examples/getting_started/zk.yaml, docs/modules/hbase/examples/getting_started/zk.yaml.j2, tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1020
=> chore: Update ZooKeeper to 3.9.3 pre-25.3.0

docs/modules/hbase/examples/getting_started/hdfs.yaml, docs/modules/hbase/examples/getting_started/hdfs.yaml.j2, tests/test-definition.yaml
part of https://github.com/stackabletech/docker-images/issues/1018
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: Update HDFS to 3.4.1

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, deploy/helm/hbase-operator/Chart.yaml, deploy/helm/hbase-operator/crds/crds.yaml, docs/antora.yml, docs/modules/hbase/examples/getting_started/getting_started.sh, docs/modules/hbase/examples/getting_started/install_output.txt, docs/modules/hbase/examples/usage-guide/hbck2-job.yaml, docs/modules/hbase/examples/usage-guide/snapshot-export-job.yaml, docs/templating_vars.yaml, tests/release.yaml
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
=> chore: Release 25.3.0

tests/templates/kuttl/logging/01-install-hbase-vector-aggregator.yaml
Part of: https://github.com/stackabletech/docker-images/issues/1146
=> chore: bump vector chart to 0.43.0

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, deploy/helm/hbase-operator/crds/crds.yaml, rust/operator-binary/src/main.rs
Part of https://github.com/stackabletech/issues/issues/733. This adds the EoS checker to the operator.
=> feat: Add EoS checker
